### ISSUE TITLE
http://{公网IP}:8888/images/ xxx.jpg 就可以访问不到图片

### ISSUE THREAD

**Issue by Hvictory1** [greenPaoPao/collegeVol#2]
用于项目学习，我的api访问不到图片

**Comment by fuheihei** [comment]
得看你是哪张图片了，一般是http://127.0.0.1:8888/images/1.jpg，这样的格式是可以访问的，你试试呢

**Comment by Hvictory1** [comment]
> 得看你是哪张图片了，一般是[http://127.0.0.1:8888/images/1.jpg，这样的格式是可以访问的，你试试呢](http://127.0.0.1:8888/images/1.jpg%EF%BC%8C%E8%BF%99%E6%A0%B7%E7%9A%84%E6%A0%BC%E5%BC%8F%E6%98%AF%E5%8F%AF%E4%BB%A5%E8%AE%BF%E9%97%AE%E7%9A%84%EF%BC%8C%E4%BD%A0%E8%AF%95%E8%AF%95%E5%91%A2)

为什么 我这边http://127.0.0.1:8888 不在以下 request 合法域名列表中 这个是你本地开的吗

**Comment by fuheihei** [comment]
我知道了，你试下将这边注释的两个方法释放开
https://github.com/greenPaoPao/collegeVol/blob/master/backend/src/main/java/com/collegevol/config/WebConfig.java
这块逻辑我后面更新下
